waf:
  mode: "protection"  # protection, monitoring, learning
  block_threshold: 0.7
  max_request_size: 10485760  # 10MB
  
  logging:
    level: "INFO"
    file: "waf.log"
    max_size: 104857600  # 100MB
  
  rule_engine:
    enabled: true
    update_interval: 3600  # 1 hour
    rules_file: "config/default_rules.yaml"
  
  anomaly_engine:
    enabled: true
    training_samples: 1000
    retrain_interval: 86400  # 24 hours
    model_file: "models/anomaly_model.pkl"
  
  rate_limiting:
    enabled: true
    requests_per_minute: 100
    burst_limit: 50
  
  behavioral_analysis:
    enabled: true
    session_timeout: 1800  # 30 minutes
    max_sessions_per_ip: 100